### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by dezhniuk** [dezhniuk/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by duo23** [comment]
- https://ru-ru.facebook.com/DonaldTrump/

- https://www.instagram.com/realdonaldtrump/

- https://twitter.com/realdonaldtrump

- https://www.whitehouse.gov/people/donald-j-trump/
